### ISSUE TITLE
Prevent players from collecting bounties on themselves by accidental death

### ISSUE THREAD

**Issue by azokthedefiler1** [Polymeta/RBounty#1]
Players on my server have figured out how to collect bounties on themselves by using methods where they are the cause of their own death (not /suicide). Would it be possible to add an extra check to the bounty detection so that this cannot happen?

File: EntityDeath.java
Line: 48
Add check like: "killer != killed"

Otherwise, the plugins works perfectly.

I'm using version 2.0.4, git cloned and compiled locally.

**Comment by Polymeta** [comment]
Sorry! took me forever to get back to you, but put in the suggested check and should be fine now :)
